webtalk_init -webtalk_dir C:/Users/matsg17/Desktop/ele112/fpga_accelerometer/fpga_accelerometer.sim/sim_1/impl/timing/xsim.dir/tb_spi_master_time_impl/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Apr 19 18:46:17 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1909853" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c7ab7bfa-150c-435a-b216-a640c4f116cb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "c191c17362314ab99b749d4185f77a2d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3392 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "21.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "101 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.47_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "9964_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4008809189 -regid "" -xml C:/Users/matsg17/Desktop/ele112/fpga_accelerometer/fpga_accelerometer.sim/sim_1/impl/timing/xsim.dir/tb_spi_master_time_impl/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/matsg17/Desktop/ele112/fpga_accelerometer/fpga_accelerometer.sim/sim_1/impl/timing/xsim.dir/tb_spi_master_time_impl/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/matsg17/Desktop/ele112/fpga_accelerometer/fpga_accelerometer.sim/sim_1/impl/timing/xsim.dir/tb_spi_master_time_impl/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
