# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.cache/wt [current_project]
set_property parent.project_path D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.srcs/sources_1/new/components.vhd
  D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.srcs/sources_1/new/counter.vhd
  D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.srcs/sources_1/new/delay_logic.vhd
  D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.srcs/sources_1/new/prescaler.vhd
  D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.srcs/sources_1/new/select_logic.vhd
  D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.srcs/sources_1/new/shiftlne.vhd
  D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.srcs/sources_1/new/spi_master.vhd
  D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.srcs/sources_1/new/data_transition.vhd
  D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.srcs/sources_1/new/signed_to_bcd.vhd
  D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.srcs/sources_1/new/bcd_to_sevenseg.vhd
  D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.srcs/sources_1/new/converter_sevenseg.vhd
  D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.srcs/sources_1/new/driver_sevenseg.vhd
  D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.srcs/sources_1/new/data_update.vhd
  D:/fpga_accelerometer/fpga_accelerometer/fpga_accelerometer.srcs/sources_1/new/counter_driver.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Skrivebord/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files E:/Skrivebord/Nexys4DDR_Master.xdc]


synth_design -top data_transition -part xc7a100tcsg324-1


write_checkpoint -force -noxdef data_transition.dcp

catch { report_utilization -file data_transition_utilization_synth.rpt -pb data_transition_utilization_synth.pb }
